export enum EGitLabels {
    Bug = 1,
    Sugestion = 2,
    Mobile = 3,
    Desktop = 4,
}

export enum MusicGenres {
    AlternativeRock = 1,
    ClassicRock = 2,
    HardRock = 3,
    ProgressiveRock = 4,
    PsychedelicRock = 5,
    PunkRock = 6,
    GlamRock = 7,
    IndieRock = 8,
    Grunge = 9,
    BluesRock = 10,
    GarageRock = 11,
    SouthernRock = 12,
    StonerRock = 13,
    HeavyMetal = 14,
    ThrashMetal = 15,
    DeathMetal = 16,
    BlackMetal = 17,
    PowerMetal = 18,
    SymphonicMetal = 19,
    ProgressiveMetal = 20,
    FolkMetal = 21,
    DoomMetal = 22,
    GothicMetal = 23,
    IndustrialMetal = 24,
    NuMetal = 25,
    SpeedMetal = 26,
    AlternativeMetal = 27,
    SludgeMetal = 28,
    Metalcore = 29,
    Deathcore = 30,
    GrooveMetal = 31
}